### ISSUE TITLE
Driver cannot load external javascripts

### ISSUE THREAD

**Issue by attilagyorffy** [smparkes/capybara-envjs#12]
I am trying to use the driver under Rails and Cucumber. Everything works fine, apart from the external javascripts. I am getting a WARNING:

WARNIING:   [Wed May 19 2010 14:11:41 GMT+0100 (BST)] {ENVJS} could not load script http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js: No route matches "/ajax/libs/jquery/1.4.2/jquery.min.js" with {:method=>:get}

My javascript sits in a static javascript include tag in the head of the html markup. (Same happens to document/write blocks too by the way.)

I am running on Rails 2.3.5 with the following gem versions:
http://gist.github.com/406343 (output from rake gems, relevant to capybara-envjs)

I've set Capybara to use envjs as the javascript driver:
Capybara.javascript_driver = :envjs

**Comment by smparkes** [comment]
Confirmed.

**Comment by smparkes** [comment]
Will be fixed in 0.1.3.

Note that it just wasn't handling off-site scripts at all, under rack-test, which I didn't realize. I thought it did. I use that with envjs but I haven't used it with capybara, I guess.

It still doesn't handle off-site pages ... not sure if that's good or bad ...
