### ISSUE TITLE
do not raise TimeoutError in wait_until method

### ISSUE THREAD

**Issue by rsim** [smparkes/capybara-envjs#13]
I have issue that in some test involving Ajax my
page.should have_css(...)
expectations were failing with Capybara::TimeoutError exception and what I found out that the reason was that Capybara::Driver::Envjs#wait_until was raising it when all javascript events were finished but before final verification if specified css selector is in the page. So I made monkey patch commenting out raising of this exception:

```
::Capybara::Driver::Envjs.class_eval do
  def wait_until max
    fired, wait = *browser["Envjs"].wait(-max*1000)
    # RSI: do not raise error as then WaitUntil.timeout is not executing passed block
    # for the last time after all events are processed
    # raise Capybara::TimeoutError if !fired && wait.nil?
  end
end
```

and now my tests are passing as after completion of this wait_until method Capybara checks for the last time if css selector is present.

If necessary I could try to create a test case that repeats this issue.

**Comment by smparkes** [comment]
If you have a test, that would be great.

Have you run the capy tests w/this change? I would think this would break them. I'm pretty sure that's how capy wants timeouts to be delivered and w/o the raise, I don't think it's going to timeout correctly.

It sounds like something related is going wrong. If fired is false, the call shouldn't have done anything and so no changes should have occurred. So whatever changes occurred should have been seen earlier.

It sounds like this isn't what you're seeing though.

A test case would help me untangle this.

**Comment by rsim** [comment]
I cannot repeat the issue in my application with the latest versions of envjs and capybara-envjs and also cannot find with which previous versions I got the issue. So you can close this issue until I manage to repeat it :)
