### ISSUE TITLE
Won't intall from gem bundler

### ISSUE THREAD

**Issue by fullofcaffeine** [smparkes/capybara-envjs#16]
I'm trying to include capybara-envjs in my Gemfile and install it using bundler (0.9.26), but it just hangs while fetching source (not sure if it hangs while or after fetching sources though). If I remove capybara-envjs from my Gemfile, everything works fine.

It just outputs:
Fetching source index from http://gemcutter.org/
Fetching source index from http://gems.github.com/

And stays there forever.

Any ideas?

**Comment by dennisreimann** [comment]
This was most likely due to the rubygems.org DNS downtime... can you try it again?

**Comment by smparkes** [comment]
Any update? Did retrying work? Can we close?

**Comment by fullofcaffeine** [comment]
Hi,

No, I haven't tried again. I actually ended up choosing Celerity (Culerity) over EnvJS this time, I will try again this weekend and report my findings,

Marcelo.

**Comment by dennisreimann** [comment]
For me it works fine:

Installing stackdeck (0.2.0) from rubygems repository at http://gemcutter.org/ 
Installing johnson (2.0.0.pre3) from rubygems repository at http://gemcutter.org/ with native extensions 
Installing envjs (0.3.6) from rubygems repository at http://gemcutter.org/ 
Installing capybara-envjs (0.1.5) from rubygems repository at http://gemcutter.org/

I really think this was related to the DNS downtime of rubygems.org...

**Comment by smparkes** [comment]
I'm going to go ahead and close this. Post new if it's still an issue.
