### ISSUE TITLE
select("something", :from => "something else") changes the state of all SELECTs that have a matching OPTION

### ISSUE THREAD

**Issue by timcowlishaw** [smparkes/capybara-envjs#18]
Hey there,

I've spent quite a while trying to work this out with no avail (it's sent me deep into the guts of envjs xpath parser with nothing really to show for it), so I'd be really grateful if you could take a look and / or give me some pointers. Basically the problem is, calling select("some option", :from => "some select") will select ALL the matching &lt;option&gt;s on the page within their respective &lt;select&gt;s - effectively ignoring the :from argument.

I've written a failing test based on a slight modification to the upstream capybara test suite:

diff from http://github.com/jnicklas/capybara commit a94f9949d5c13e73b115fb6b2a9774214e6fb813: http://gist.github.com/451651

I've tracked the problem down as far as the call to xpathParse at line 33 of src/xpath/expression.js in the env-js source (this is from your (smparkes's) fork btw). For some reason that I can't work out, this sets the 'absolute' property to true on the result it sends back (this happens at line 1697 of src/xpath/implementation.js although I'll be damned if i can work out why or where it gets called from), meaning that when evalute() is called on the returned object, it searches within context.root, rather  than context.node, returning all the matching &lt;option&gt;s in the document.

Any pointers as to how we can remedy this would be great!

Cheers,

Tim

**Comment by smparkes** [comment]
Thanks for the test. I submitted it to Jonas. And I fixed the issue. It's pushed to git now but I haven't released a patched gem (yet). Waiting to hear if Jonas is ready for 0.3.9.

**Comment by timcowlishaw** [comment]
No problem  at all - thanks very much! Looking at your change, I see that I would have been more useful at finding the problem had I only known xPath :-)

**Comment by smparkes** [comment]
0.1.6 pushed
