### ISSUE TITLE
Any example code?

### ISSUE THREAD

**Issue by millisami** [smparkes/capybara-envjs#2]
I like to use it with rails app. But couldn't figure out how to get started.
Any example code or app would be much better as a getting started.

**Comment by smparkes** [comment]
Did you look at the Capybara docs (http://github.com/jnicklas/capybara)? There's nothing particularly special about using the envjs driver. All the Capybara docs apply.

The capybara specs serve as good examples for writing rpsec tests with capybara. That's not in the context of a Rails application, but rpsec is pretty generic.

Capybara also works with Cucumber, and envjs is supported as normal. I did some bare testing with Cucumber, but I don't use it much so don't have any demos.

**Comment by millisami** [comment]
ok, i'll look into it.

**Comment by smparkes** [comment]
Great. Good luck. There are a bunch of people on the Google group, so that's a great place to ask questions.

**Comment by smparkes** [comment]
jxon also put together a demo: http://github.com/jxson/envjs-cucumber-example
