### ISSUE TITLE
Rails 3 link_to remote=true followed as HTML instead of JS

### ISSUE THREAD

**Issue by Florent2** [smparkes/capybara-envjs#23]
I have a link_to with remote=true in a view that I want to test in a Cucumber scenario with capybara-envjs (using @javascript tag). When the user click this link it submits a request to a "get_more" controller action. 

With my browser it works, as the browser correctly submits the link with HTTP_ACCEPT "text/javascript, application/javascript".

When I run the scenario, it does not work as I get the error

 Missing template announcements/get_more with {:handlers=>[:rxml, :builder, :rjs, :haml, :rhtml, :erb], :formats=>[:html], :locale=>[:en, :en]} in view paths "/Users/Florent/Programmation/Projets/myapp/app/views", "/Users/Florent/.rvm/gems/ree-1.8.7-2010.01/gems/devise-1.1.rc2/app/views" (ActionView::MissingTemplate)

Rails is looking for a HTML template instead my javascript template. Looks like the request is not submitted by capybara-envjs with the correct HTTP_ACCEPT "text/javascript, application/javascript" header.

Is this a bug or is there a way to force capybara-envjs HTTP_ACCEPT header? (BTW thanks a lot for you gem it is very useful!)

**Comment by smparkes** [comment]
It sounds we're not sending the header.

Do you have an example. so I can double check?

**Comment by wicz** [comment]
The headers aren't being sent. I fixed in my fork, see commit [e134bd2](http://github.com/wicz/capybara-envjs/commit/e134bd2604a43eced89cc127b6b8fddc446b2675).

If you can't get it working, drop me a line. I'll be glad to help and write some tests.

**Comment by smparkes** [comment]
Thanks. I'll try to look at this this weekend.

**Comment by smparkes** [comment]
Committed. Thanks!

**Comment by scottkf** [comment]
Sorry to bring this back up, but you committed this, I see, but it hasn't been rolled into the gem yet it looks like.

**Comment by smparkes** [comment]
Yeah. capy-envjs master requires capy master. I'm waiting on Jonas for a new release.
