### ISSUE TITLE
check alert message in a Cucumber step?

### ISSUE THREAD

**Issue by Florent2** [smparkes/capybara-envjs#24]
Hello,

Is there a way to check the content of a javascript alert() message? When running my feature I can see that envjs correctly 'sees' the alert() message (I get "WARNIING:       [Sat Jul 10 2010 16:01:56 GMT-0500 (PET)] {ENVJS} You must enter a message.") but I don't how to check this a Cucumber step.

**Comment by smparkes** [comment]
Does capybara have a way of doing this? capybara-envjs is a driver and only provides access to what the capybara interface provides.

Have you asked this on the capy list?

**Comment by Florent2** [comment]
No, I'll do that. Thanks!

**Comment by Florent2** [comment]
Finally I could see the alert message just with have_content... Sorry!

**Comment by smparkes** [comment]
Really? I wonder if you're actually seeing that the alert JS source in there. I wouldn't think have_content would allow you see if the alert had actually fired (if that's what you're trying to test).

**Comment by Florent2** [comment]
Yes that's why I'm trying to test... and you're right, indeed it just see the JS source... (I need a bit of rest :) )

I'll ask in the capybara ml.
