### ISSUE TITLE
redirects after a POST

### ISSUE THREAD

**Issue by h-lame** [smparkes/capybara-envjs#26]
When capybara-envjs follows redirects after a POST, the headers like CONTENT_TYPE and CONTENT_LENGTH are sent along with the GET that fetches the redirect.  This doesn't present a problem with the sinatra based test app, but it does in rails apps as rails will barf on the fact that the headers say there is some data in the request, but it's not there (Sinatra is probably wrong in not barfing).

The super simple fix is here: http://github.com/h-lame/capybara-envjs/commit/36c811bfa3aa9d67ca0861ce473776331fe159b0

I've no idea how to test it though (as the Sinatra test app doesn't seem to break!)

**Comment by smparkes** [comment]
Looks good to me. Thanks!
