### ISSUE TITLE
XPath Failure: v1 is undefined

### ISSUE THREAD

**Issue by kendagriff** [smparkes/capybara-envjs#28]
I've got a fairly standard setup: cucumber, capybara, and I'd now like to throw envjs in there.

Capybara.default_selector = :css
Capybara.javascript_driver = :envjs

I run a cucumber test, with javascript on, and here's the output:

Using the default profile...
not implmented yet: XPath function local-name()
xpath failure: TypeError: v1 is undefined
 WARNIING:  [Fri Aug 06 2010 13:24:45 GMT-0600 (MST)] {ENVJS} could not load script http://www.example.com/javascripts/prototype.js?1280583605: v1 is undefined
 WARNIING:  [Fri Aug 06 2010 13:24:45 GMT-0600 (MST)] {ENVJS} could not load script http://www.example.com/javascripts/controls.js?1280583605: Field is undefined
 WARNIING:  [Fri Aug 06 2010 13:24:45 GMT-0600 (MST)] {ENVJS} could not load script http://www.example.com/javascripts/rails.js?1280583605: document.observe is not a function

**Comment by smparkes** [comment]
See http://github.com/smparkes/capybara-envjs/issuesearch?state=open&q=prototype#issue/1.

**Comment by sobrinho** [comment]
Updating prototype to latest version fix this (Prototype 1.7.rc2) ;)

**Comment by smparkes** [comment]
Cool. Thanks for letting us know.
