### ISSUE TITLE
Capybara can't find the envjs driver

### ISSUE THREAD

**Issue by olivernn** [smparkes/capybara-envjs#3]
I have installed the capybara-envjs gem along with the envjs gem and the johnson gem however when I set the driver with 
    Capybara.default_driver = :envjs
I get the error 'no driver called envjs was found (Capybara::DriverNotFoundError)', am I missing something?

**Comment by smparkes** [comment]
What versions of everything do you have installed, i.e., gem list?

You need capy 3.6. I'll be updating the envjs driver to spec that soon.

**Comment by smparkes** [comment]
I've just pushed a non-pre release of the envjs driver. Can you try upgrading to that and see if you still have issues?

**Comment by olivernn** [comment]
I'm still getting the 'no driver called envjs' error.

I've upgraded the gems to the following versions:
capybara: 0.3.6
capybara-envjs: 0.1.0
envjs: 0.3.0
johnson: 2.0.0.pre3

I'm setting the default driver with the following line
    Capybara.default_driver = :envjs

**Comment by smparkes** [comment]
Hmmm ... Can you try this:

First, make sure Johnson can start okay: just type "johnson" at the command line. It should give you a "js>" prompt (just ctrl-d out of it).

Also, check if what errors you get trying to load the driver: use irb:

irb
require 'rubygems'
require 'capybara/envjs'

**Comment by olivernn** [comment]
Johnson starts fine from the command line, I get the js> prompt.  In irb there is no error when loading the 'capybara/envjs' gem.

I'm not sure what else there is I can do to try and get to the bottom of this, I'll play around a little more to see if it is something obvious I'm missing.

**Comment by smparkes** [comment]
Okay. Lets step this up a little. Can you clone the capybara-envjs repo and try to run the tests?

git clone git://github.com/smparkes/capybara-envjs.git
cd capybara-envjs
rake

See where that gets us. We can start putting in debug statements as necessary.

What kind of tests are you trying to run, e.g., rspec, cucumber?

I just pushed a really base-bones Rails app that I use to smoke-test cucumber (which I haven't used much yet): http://github.com/smparkes/test-capy

**Comment by olivernn** [comment]
I tried to run the tests for capybara-envjs project, however it failed, the error is in this gist - http://gist.github.com/350531

I want to use this to be able to use cucumber to drive some javascript parts of an app, currently I'm using selenium which works ok but it is quite slow.

**Comment by smparkes** [comment]
Okay, I've replicated this on my macbook. I had it on linux, too, yesterday but it went away. More soon.

**Comment by smparkes** [comment]
The has_select issue is a capybara gem packaging issue.  If you clone capyabara, then do a "rake check_manifest | patch", and "rake gem", it'll create a version of the gem in pkg that you can install which will have the missing files until upstream gets to it.

Then, I suspect, we'll be back to the real issue, which I still don't really understand.

Can you try my demo repo and see if it works? There may be settings that I have that I don't realize.

Also, what are you running this on? If you have johnson installed, you should be okay, but curious ...

**Comment by jxson** [comment]
I had this issue pop up for me, by accident I realized by removing my World block from my env.rb that the 'no driver called envjs was found' error went away..

**Comment by smparkes** [comment]
Okay. I've just checked with capy 3.7 and you should be able to run the exiting driver and its tests from a normal gem install of it (capy 3.7).

We can reopen this if there are still issues getting things running.

**Comment by smparkes** [comment]
Hmmm ... how do I actually run the tests in this thing? (Sorry; I'm not too cucumber-literate, and what I've done with it has been in the context of rspec.

**Comment by aspiers** [comment]
I get the 'no driver called envjs' error too, even though both the johnson and irb tests above work fine.  I don't have a World block in my env.rb.  Currently trying to pin it down ...

**Comment by aspiers** [comment]
I'm stuck on this.  I tried running rake from /usr/lib/ruby/gems/1.8/gems/capybara-envjs-0.1.6 to ensure the test suite passed.  Firstly I had to manually install the sinatra gem to fix an error that it wasn't there - it looks like capybara-envjs has a missing dependency on it.

Secondly I had to manually patch lib/rack/utils.rb to fix a bug related to Regexp.union on Ruby 1.8.6.  Finally this got me a passing test suite:

(in /usr/lib/ruby/gems/1.8/gems/capybara-envjs-0.1.6)
warning: couldn't activate the debugging plugin, skipping
warning: couldn't activate the doofus plugin, skipping
warning: couldn't activate the git plugin, skipping
/usr/lib/ruby/gems/1.8/gems/capybara-0.3.9/lib/capybara/spec/driver.rb:165: warning: parenthesize argument(s) for future version
/usr/lib/ruby/gems/1.8/gems/capybara-0.3.9/lib/capybara/spec/driver.rb:170: warning: parenthesize argument(s) for future version
/usr/lib/ruby/gems/1.8/gems/capybara-0.3.9/lib/capybara/spec/driver.rb:175: warning: parenthesize argument(s) for future version
/usr/lib/ruby/gems/1.8/gems/capybara-0.3.9/lib/capybara/spec/driver.rb:177: warning: parenthesize argument(s) for future version
/usr/lib/ruby/gems/1.8/gems/capybara-0.3.9/lib/capybara/spec/driver.rb:181: warning: parenthesize argument(s) for future version
/usr/lib/ruby/gems/1.8/gems/capybara-0.3.9/lib/capybara/spec/driver.rb:183: warning: parenthesize argument(s) for future version
......................................................................................................................................................................................................................................................................................................................................... WARNIING:   [Sun Oct 24 2010 15:16:58 GMT+0100 (BST)] {ENVJS} Exception while processing XHR: redirected more than 5 times, check for infinite redirects.
 WARNIING:      [Sun Oct 24 2010 15:16:58 GMT+0100 (BST)] {ENVJS} Exception while loading window: redirected more than 5 times, check for infinite redirects.
..................

Finished in 185.265048 seconds

347 examples, 0 failures

I am using the master branch from git://github.com/jnicklas/capybara.git together with: 

   ruby 1.8.6 (2010-02-05 patchlevel 399) [i386-linux] 
   cucumber (0.9.2) 
   cucumber-rails (0.3.2) 
   selenium-webdriver (0.0.29)

Any suggestions on what else to check would be greatly appreciated.  I can even arrange remote access to my system if that helps.

**Comment by smparkes** [comment]
Not the core issue, but 1.8.6 is known to not work with Johnson: conflicting garbage collectors in Ruby and Javascript. 1.8.7 has no known issues.

As to the driver issue, I just integrated some of Jonas patches to the gemspec/driver stuff. Could you try that? You should be able to use the git repo as a gem reference in bundler gemfile now which should make that easier.

**Comment by aspiers** [comment]
I'm still on Rails 2.3.x so no bundler.  However, it has been long enough since I looked at this that 0.4.0 has come out, so I have upgraded to that and don't see the issue now.

If Johnson is known not to work with 1.8.6 then I am puzzled why it installed successfully - surely there should be a dependency check in the gem to catch this?  Should I submit a new issue for the missing dependency at https://github.com/jbarnette/johnson/issues ?  Thanks!

**Comment by smparkes** [comment]
Glad it's working.

As to 1.8.6, you can open an issue if you'd like. Even better if you have a patch (I've actually not done any gemspec customization that aligns the ruby version settings). Even more than 1.8.6, it shouldn't allow trying to install on 1.9 since it won't even compile there.

I'm not sure which set of tests failed on 1.8.6. I should have taken a snapshot for future testing. I don't think it was the johnson unit tests. It has to do with the garbage collector, I think, which is difficult to consistently test.

**Comment by aspiers** [comment]
I submitted a [new issue](https://github.com/jbarnette/johnson/issues/issue/38) to Johnson about the lack of dependency checking against the Ruby version.  I found [Gem::Specification::required_ruby_version](http://docs.rubygems.org/read/chapter/20#required_ruby_version) but I don't know how you'd use this from Hoe.
