### ISSUE TITLE
Missing these required gems:   capybara-envjs  

### ISSUE THREAD

**Issue by rtacconi** [smparkes/capybara-envjs#32]
When I run 'rake test' I get:

Missing these required gems:
  capybara-envjs  

You're running:
  ruby 1.8.7.248 at /Users/riccardotacconi/.rvm/rubies/ree-1.8.7-2010.01/bin/ruby
  rubygems 1.3.7 at /Users/riccardotacconi/.rvm/gems/ree-1.8.7-2010.01@global, /Users/riccardotacconi/.rvm/gems/ree-1.8.7-2010.01
## Run `rake gems:install` to install the missing gems.

I have: 

johnson (2.0.0.pre3)
capybara (0.3.9)
capybara-envjs (0.1.6)
RAILS_GEM_VERSION = '2.3.8'

I am loading Capybara from environment.rb in this way:

require 'capybara/rails'
require 'capybara/dsl'
require 'capybara/envjs'
Capybara.javascript_driver = :envjs

Capybara is used inside shouda and I do not have any Cuke or RSpec.

Please advice.

**Comment by smparkes** [comment]
I'm sorry but I'm really not sure. I've never seen anything like this. It sounds like something is confused with your gem setup.

**Comment by rtacconi** [comment]
Is there an example on how to use capybara and capybara-envjs without RSpec and Cucumber?

**Comment by rtacconi** [comment]
after a 'gem update' I get 

/opt/local/apache2/rails_data/qna/config/../vendor/rails/railties/lib/initializer.rb:271:in `require_frameworks': can't activate rack (~> 1.1.0, runtime) for [], already activated rack-1.2.1 for ["capybara-0.3.9"](RuntimeError)

**Comment by rtacconi** [comment]
with this is ok: config.gem 'rack', :version => '1.1.0'

But I am still getting the same error.

**Comment by rtacconi** [comment]
Issue solved. In environment.rb I put the :lib symbol and capybara-envjs started to work:

config.gem 'capybara-envjs', :version => '0.1.6', :lib => 'capybara/envjs'

**Comment by smparkes** [comment]
Great!
