### ISSUE TITLE
show me the page doesn't work with envjs

### ISSUE THREAD

**Issue by sdillard** [smparkes/capybara-envjs#35]
I have a test that is not working, and normally I would put in a "show me the page" so I can see what was being read at the time, but this doesn't seem to work with envjs.  When I tag my feature with @javascript, it fails, and the result of showing the page is just a file with "No File".  Any suggestions on how to capture the page output at that point and save it as a file?

**Comment by smparkes** [comment]
Is "show me the page" a capy thing? I seem to remember a feature like that, but I haven't used it so I don't remember the details. What I do remember worked, though.

However, there are also two capy options, as I remember, available from the session. body and source, one being the page as fetched and the other being a live version of the DOM (as updated by any javascript in the page).

**Comment by sdillard** [comment]
Thanks for the quick response!

There are two methods I use: show me the response and show me the page
Show me the response does a "puts response.body"
Show me the page does a "save_and_open_page" invocation (yes, it's a capy method)

But interestingly, when I created 2 new steps that are specific to a javascript-based feature, and I output the body, I am seeing the same thing, so it seems to be working but something else is causing it to not go to the page.  I think I need to write a basic feature to make sure env-js is working correctly before worrying about whether my code is broken.  Will post again if I find the solution, but it appears to be my issue.
I'll

**Comment by smparkes** [comment]
Yeah, you may be hitting a corner where env-js is incomplete, particularly if it works with one of the other javascript drivers.

**Comment by sdillard** [comment]
I'm just plain confused at this point... I can run a rudimentary test that eval's a js function and verifies the return value is what is expected, so I know everything is getting loaded and running.

But, the second scenario fails.  Here they are:

```
Feature: Enable JavaScript-based Testing
  As a developer
  I want to be able to test javascript
  so I can know my code is working if javascript is enabled

  @javascript
  Scenario: Make sure JavaScript test driver loads
    Given I execute a basic JavaScript statement
    Then the JavaScript statement should return what I expected

  @javascript
  Scenario: Make sure Javascript works
    Given I visit the external site "http://jquery.com"
    Then show me the javascript response
    And I should see "JavaScript library"
    And the default host settings should be restored
```

the response is coming back as an empty page with just head, title, and body tags.  The relevant matchers look like this:

```
Given /^I execute a basic JavaScript statement$/ do
  @js_to_eval = "var jsEvalFunction = function() { var x = 10; var y = 20; return (x + y).toString(); }; jsEvalFunction();"
  @js_expected_outcome = "30"
end

Then /^the JavaScript statement should return what I expected$/ do
  evaluate_script(@js_to_eval).should == @js_expected_outcome
end

Then /^show me the javascript page$/ do
  save_and_open_page
end

Then /^show me the javascript response$/ do
  puts body
end

#Make sure the matcher to restore settings is always invoked after this
Given /^I visit the external site "(.+)"$/ do |site|
  @app_host = Capybara.app_host
  Capybara.app_host = site
end
#Make sure this is always invoked when visit external site is used, otherwise all future tests will fail
Then /^the default host settings should be restored$/ do
  Capybara.app_host = @app_host
end
```

It seems that the visit method is not working in capybara, which seems rather fundamental.  I also added a method to force capybara to go to a site, and I've tried with this and with the standard web step to visit a path.  I'm not trying to get you to solve my issues here -- just trying to figure out where envjs can go and where I am pushing prematurely.

**Comment by smparkes** [comment]
Visit shouldn't be an issue, bugs notwithstanding. But all that should be orthogonal to javascript, right?

I'm not sure exactly what you're trying to accomplish with the app_host manipulation. For one thing, I'm not sure what the scope of member variables is in a test; maybe that's fine, but you might want to use another name.

Moreover, you might need to slam both app_host and default_host if you're trying to capture an external URL.

Oh, and you might need to be on master capy-envjs if that is what you're trying to do.

**Comment by sdillard** [comment]
Right -- I really don't want to force the app_host or default_host, but I tried without it and no luck, so it was somewhat of an experiment.  I was finding that without it, the test was still calling my local server but then evaluating it as if it were the external site.  

I tried setting both the default_host and app_host and changed my variable names (good point), but still no luck.  I just get a blank page.

Will try switching to the master, but I may have to punt for now, as that may start cascading into multiple dependency conflicts (using rails 2.3.9 with bundler 1.0).

**Comment by smparkes** [comment]
If you're not trying to do anything against app_host/default_host, you shouldn't need master.

I'm pretty confused about your visit step: it's not actually fetching anything. Setting the variables in there will affect where things get fetched from, but you do have to do a visit in there somewhere. The HTML you said you're seeing is the minimal HTML doc you'll see if you don't actually do a visit (or, in JS, set the window.location).

**Comment by sdillard** [comment]
You're correct about the step, but the issue is still there.  I was just losing it trying to figure out what was going on that I missed the all important part of the step -- visiting the site.  But, after fixing it (and hitting myself on the head), I am still seeing my local page.

Thanks again for the responses.  I spent more time researching, and it appears that there is an issue with capybara that it is using its own, modified version of rack-test, which doesn't allow you to go off to another site.  When I changed my test to verify some basic javascript on my root page, it all worked well.  So, sorry to waste your time, but hopefully this helps someone else.

**Comment by smparkes** [comment]
The rack-test thing may not be at issue; I'm not sure. The envjs driver is separate from the standard capy rack-test driver, though it's modeled in large part on it.

As far as I know, if you visit a site that isn't app_host/default_host, it should fetch it, though there may be bugs there. I'm pretty sure it will hit it if you navigate it via JS, but it may be the visit path is different.

If you want to push a test to github somewhere, I can try it and see. I'm curious as to if the current master branch fixes this, since it cleans up some of the host matching stuff.
