### ISSUE TITLE
oopse element.contentWindow is undefined

### ISSUE THREAD

**Issue by bcardarella** [smparkes/capybara-envjs#38]
I'm pretty sure I have a standard capybara-envjs install. Rails 3, Cucumber 0.9.3. I'm getting the following error:

http://pastie.org/1249517

element.contentWindows appears to be undefined for some reason. Thoughts?

**Comment by bcardarella** [comment]
Nevermind, this seems to be an issue with the jquery.wysiwyg library.

**Comment by smparkes** [comment]
Ah. Okay. Thanks!
