### ISSUE TITLE
click_button is not triggering a submit or click event

### ISSUE THREAD

**Issue by jxson** [smparkes/capybara-envjs#4]
I am almost up and running with the envjs driver but am having a problem that makes it look like my event handlers are not being triggered.

inside of one of my steps I have:
click_button(button)

And in my js I have a submit event handler for the form which is not being triggered.

The event is triggered when I do something like this from a step:
page.evaluate_script("$('#login-button').click();");

I was thinking it may have something to do with needing wait wait_until but I am unsure...

**Comment by smparkes** [comment]
I'll look at this. There are some corner cases where we might not have events wired up 100% but basic clicks should be fine.

Do you have small example that shows this?

**Comment by jxson** [comment]
I will put something together tonight

**Comment by smparkes** [comment]
Thanks. I should have time to look at it this week.

**Comment by jxson** [comment]
Alright, I put together a little example app for you to take a look at

http://github.com/jxson/envjs-cucumber-example

Thanks so much for this by they way, the envjs driver is pretty freaking awesome!

**Comment by smparkes** [comment]
Hmm ... I thought I commented on this already ...

Is there some way to run the tests in your repo? I'm used to using Rake to run rspec tests ... beyond that, I'm not terribly cucumber savy.

**Comment by jxson** [comment]
I just added a rake task for ya:

rake cucumber

you can also use cucumber directly like this:

cucumber features/events.feature

But I recommend the rake task since it defines the gem dependencies (sinatra, rspec, rack-test, cucumber, capybara, capybara-envjs) in case your missing something

**Comment by smparkes** [comment]
Great. Thanks. That's a great help.

It's the failure of the form submission that should be working, right?

**Comment by jxson** [comment]
yeah exactly,

it seems the click_button on line 22 of features/step_definitions/web.rb to be the culprit...

**Comment by smparkes** [comment]
Actually, this wasn't a driver issue, but an env-js issue. preventDefault was not hooked up. Fixed in envjs-0.3.3.

Note that the event code has been reworked upstream and needs to be merged, so you might find other corner cases (though we've been knocking them down one by one).
