### ISSUE TITLE
EnvJS encountering "unmatched ) in regular expression" in jQuery

### ISSUE THREAD

**Issue by btelles** [smparkes/capybara-envjs#41]
Hi there,

I'm using jQuery with capybara-envjs, and ended up importing it directly into the page. Unfortunately I keep getting an error as follows:

<pre>ERROR [ ... ] {ENVJS} unmatched ) in regular expression</pre>

Immediately before the error, cucumber spits out the entire script, which is odd, and evaluating each script (i.e. the jquery library) takes about 30 seconds.

Has anyone else encountered this? If so, do you know what could be going on wrong?

**Comment by smparkes** [comment]
Doesn't sound familiar.

**Comment by btelles** [comment]
Hmmm...I added <![CDATA[ AND ]]> and it appears to work now...still having trouble getting all the stuff to work though ....feel free to delete this ticket. Thanks for the quick response.

**Comment by smparkes** [comment]
Thanks.

env.js does tend to have issues with the current version of jQuery, I'm afraid.
