### ISSUE TITLE
Ruby 1.9

### ISSUE THREAD

**Issue by Nerian** [smparkes/capybara-envjs#48]
Hi

I am trying to install Envjs in Mac Os X with ruby 1.9

In my gemfile:

gem "capybara-envjs", :git => 'https://github.com/smparkes/capybara-envjs.git'

But I get come compile time errors regarding Johnson. It seems that Johnson doesn't support ruby 1.9. It cannot compile.

Any work around on this?

**Comment by smparkes** [comment]
1.8 is the only workaround at this point. It's unclear if Johnson will ever support 1.9. At some point, env.js may support therubyracer, but I'm not sure when that will happen and it's likely the capy driver will require significant changes.
