### ISSUE TITLE
Handling ajax callbacks

### ISSUE THREAD

**Issue by stevehodgkiss** [smparkes/capybara-envjs#5]
Hi

I have forked jxson's sample sinatra app and changed the best movie ever form to use ajax and put the same response in p#result. The step _Then I should see "You think Teen Wolf is the best movie ever? Pfff..."_ now fails. Is this a limitation of the driver or is there another way to make this work?

http://github.com/stevehodgkiss/envjs-cucumber-example

Thanks

Steve

**Comment by smparkes** [comment]
Sorry. Stupid oversight on my part. Fixed in capy-envjs 0.1.2.

**Comment by stevehodgkiss** [comment]
That fixed it, thanks!
