### ISSUE TITLE
Driver is attempting to load my js files from example.com

### ISSUE THREAD

**Issue by myronmarston** [smparkes/capybara-envjs#7]
When I use capybara-envjs, I get lots of messages like:

WARNIING:   [Fri May 07 2010 22:58:49 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/application.js?1273294875: syntax error

Apparently it's trying to download the javascript from example.com rather than getting it from the public directory of my rails app.  Any idea what could be causing this?

**Comment by smparkes** [comment]
Hmmm ... I'm not entirely sure. I think the message might actually be telling you there's a syntax error in your JS. example.com is just the prefix capybara always uses when using  Rack::Test, which the envjs driver uses by default.

I just thought there'd be more information if it was a syntax error in JS. I need to double check that.

Are there any other messages? Could you post your JS?

**Comment by myronmarston** [comment]
I actually know that the issue isn't the syntax of my js, but the fact that it's trying to download it from example.com, where it gets 404 page that is in fact not valid javascript syntax.  Here's the info that leads me to that conclusion:

First off, I'm not just getting the syntax error from our custom javascript.  I'm also getting it from jQuery, jQuery UI, etc:

```
 WARNIING:  [Fri May 07 2010 22:58:48 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/modernizr.js?1273009979: syntax error
 WARNIING:  [Fri May 07 2010 22:58:48 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/jquery.js?1269647623: syntax error
 WARNIING:  [Fri May 07 2010 22:58:48 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/jquery-ui.js?1269647623: syntax error
 WARNIING:  [Fri May 07 2010 22:58:48 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/jquery.plugins.js?1273184271: syntax error
 WARNIING:  [Fri May 07 2010 22:58:49 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/jquery.tipsy.js?1269647623: syntax error
 WARNIING:  [Fri May 07 2010 22:58:49 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/jquery.countdown.js?1269647623: syntax error
 WARNIING:  [Fri May 07 2010 22:58:49 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/jquery.browser.js?1269647623: syntax error
 WARNIING:  [Fri May 07 2010 22:58:49 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/facebox.js?1266728023: syntax error
 WARNIING:  [Fri May 07 2010 22:58:49 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/application.js?1273294875: syntax error
 WARNIING:  [Fri May 07 2010 22:58:50 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/forms.js?1266728023: syntax error
```

We're using stock jQuery--we haven't modified it at all.  Also, I'm using [FakeWeb](http://github.com/chrisk/fakeweb) and I originally had `allow_net_connect` set to false.  That gave me these errors:

```
 WARNIING:  [Fri May 07 2010 22:03:50 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/modernizr.js?1273009979: Real HTTP connections are disabled. Unregistered request: GET http://example.com/javascripts/modernizr.js
 WARNIING:  [Fri May 07 2010 22:03:50 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/jquery.js?1269647623: Real HTTP connections are disabled. Unregistered request: GET http://example.com/javascripts/jquery.js
 WARNIING:  [Fri May 07 2010 22:03:50 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/jquery-ui.js?1269647623: Real HTTP connections are disabled. Unregistered request: GET http://example.com/javascripts/jquery-ui.js
 WARNIING:  [Fri May 07 2010 22:03:50 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/jquery.plugins.js?1273184271: Real HTTP connections are disabled. Unregistered request: GET http://example.com/javascripts/jquery.plugins.js
 WARNIING:  [Fri May 07 2010 22:03:50 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/jquery.tipsy.js?1269647623: Real HTTP connections are disabled. Unregistered request: GET http://example.com/javascripts/jquery.tipsy.js
 WARNIING:  [Fri May 07 2010 22:03:50 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/jquery.countdown.js?1269647623: Real HTTP connections are disabled. Unregistered request: GET http://example.com/javascripts/jquery.countdown.js
 WARNIING:  [Fri May 07 2010 22:03:50 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/jquery.browser.js?1269647623: Real HTTP connections are disabled. Unregistered request: GET http://example.com/javascripts/jquery.browser.js
 WARNIING:  [Fri May 07 2010 22:03:50 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/facebox.js?1266728023: Real HTTP connections are disabled. Unregistered request: GET http://example.com/javascripts/facebox.js
 WARNIING:  [Fri May 07 2010 22:03:50 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/application.js?1273294875: Real HTTP connections are disabled. Unregistered request: GET http://example.com/javascripts/application.js
 WARNIING:  [Fri May 07 2010 22:03:50 GMT-0700 (PST)] {ENVJS} could not load script http://example.com/javascripts/forms.js?1266728023: Real HTTP connections are disabled. Unregistered request: GET http://example.com/javascripts/forms.js
 WARNIING:  [Fri May 07 2010 22:03:50 GMT-0700 (PST)] {ENVJS} could not load script http://www.google-analytics.com/ga.js: Real HTTP connections are disabled. Unregistered request: GET http://www.google-analytics.com/ga.js
 WARNIING:  [Fri May 07 2010 22:03:50 GMT-0700 (PST)] {ENVJS} could not load script http://assets0.zendesk.com/external/zenbox/overlay.js: Real HTTP connections are disabled. Unregistered request: GET http://assets0.zendesk.com/external/zenbox/overlay.js
```

"Real HTTP connections are disabled" is the error `FakeWeb` gives you when an unregistered Net::HTTP request is made with `allow_net_connect` is set to false, which means that it's trying to request the javascripts from example.com.

I changed `allow_net_connect` to true, and now I get the syntax errors I've pasted above.

**Comment by smparkes** [comment]
Cool. That'll help a lot (knowing that it's trying to hit the real web.) So I have to things to fix: not trying to hit the web and not trying to parse 404 results as JS.

**Comment by smparkes** [comment]
One thing I'm not sure about, though, is fakeweb, what implications that has. Maybe it and the driver are stepping on each other.

Or it and capybara, actually. Or it and Rack::Test. Is fakeweb supposed to work with Rack::Test? I don't have a total handle on this, but without having dug into some of the details of this, how would we expect Rack::Test and fakeweb to work together? Rack::Test shouldn't be hitting the web at all, so why is fakeweb even getting called, if it's only trapping HTTP calls? You are trying to use Rack::Test, right, not against a live server?

I can look into this more, but if you know ...

**Comment by myronmarston** [comment]
I tried this [envjs example](http://github.com/jxson/envjs-cucumber-example) and it worked fine.  In my case, it behaves as if javascript is disabled since it's not loading any valid js, and it defeats the purpose of using envjs as I can't actually test my app's javascript functionality.

There must be something in envjs (or your driver) that figures out that it should load the js file from your file system (or make a request through rake-test to the app) rather that trying to download it from example.com.  Any idea what could be different about my app that stops that from happening?  My first thought was that I might be using absolute URLs for the javascript, but I checked, and they're relative.

**Comment by smparkes** [comment]
Not sure yet. It looks like there's a path going to the web that shouldn't be, some corner case. Could easily be in my code, but not sure yet.

How are you loading the JS? Static script tags? document.write-created script tags? XMLHTTPRequests? (These should all be funneled through the same code, but if they're not it'll help to know which one isn't working).

Do you have an example I can play with?

As you pointed out, the example uses static JS in files and I know it works with the Rack::Test path, so we just need to figure out what you're doing different and track back from there.

**Comment by myronmarston** [comment]
FakeWeb monkey patches `Net::HTTP`, and it shouldn't have an effect on any code that does not make http requests through `Net::HTTP`.  I'm using it because my app relies upon a few external HTTP APIs, such as google geocoding.  I'm using [VCR](http://github.com/myronmarston/vcr) to automatically record the http requests (saving them to YAML files like [this](http://gist.github.com/394633)), and then it hooks the recorded responses up with fakeweb so my tests are fast and deterministic, and don't rely upon an internet connection (so my cucumber suite passes when I'm on the bus, for example).

Anyhow, I think the only reason fakeweb had any effect is because something was loading the js files by making a `Net::HTTP` request.

**Comment by myronmarston** [comment]
Want to hop on an IRC room or something and chat?

**Comment by smparkes** [comment]
smparkes on #capybara@freenode (oops ... wasn't connected)

**Comment by smparkes** [comment]
Resolved as an issue with hostnames in some monkey patching ... gonna follow up on hostnames with capybara. Too many versions ...

**Comment by briandemant** [comment]
Please provide more info on how to resolve this..

**Comment by myronmarston** [comment]
This was due to a rack-test monkey patch I had in my environment.  It's not an issue for core rack-test.

**Comment by mikeymckay** [comment]
I am having the same problem (local javascript files downloading from example.com) on a simple sinatra app that I setup using the cucumber-sinatra gem: 

http://github.com/mikeymckay/wakawaka

I would appreciate some pointers for debugging this.

**Comment by mikeymckay** [comment]
Oops. Looks like it was a sinatra configuration issue. For some reason I need to manually set the public directory (it's supposed to default to public, but isn't). 

class Wakawaka < Sinatra::Base
  set :public, 'public'

  ^^^^^^^^^^^^^^^^^^

FWIW - this project is awesome and very important - well done.
