### ISSUE TITLE
error when using capybara-envjs from within rspec in a project with cucumber

### ISSUE THREAD

**Issue by mguterl** [smparkes/capybara-envjs#8]
We are using capybara / capybara-envjs with steak (vanilla RSpec plus some aliases) for acceptance testing on a project.  We are slowly replacing our Cucumber scenarios with steak, so we actually have both installed on the project.

Because of this, capybara-envjs is assuming that it is running under cucumber.  Line 4 of envjs.rb:

```
if Object.const_defined? :Cucumber
  require 'capybara/envjs/cucumber'
end
```

Because this isn't inside of Cucumber, I get a stack trace related to World being undefined on Object.  Stack trace below...

Changing the conditional to match below seems to fix the issues that I'm seeing, but I'm not sure if it will continue to work with Cucumber.

```
if Object.const_defined?(:Cucumber) && Object.respond_to?(:World)
  require 'capybara/envjs/cucumber'
end
```

/var/lib/hudson/.bundle/ruby/1.8/gems/capybara-0.3.7/lib/capybara/cucumber.rb:4: undefined method `World' for main:Object (NoMethodError)
    from /var/lib/hudson/.bundle/ruby/1.8/gems/polyglot-0.3.1/lib/polyglot.rb:64:in`polyglot_original_require'
    from /var/lib/hudson/.bundle/ruby/1.8/gems/polyglot-0.3.1/lib/polyglot.rb:64:in `require'
    from /usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:158:in`require'
    from /var/lib/hudson/.bundle/ruby/1.8/gems/capybara-envjs-0.1.2/lib/capybara/envjs/cucumber.rb:1
    from /var/lib/hudson/.bundle/ruby/1.8/gems/polyglot-0.3.1/lib/polyglot.rb:64:in `polyglot_original_require'
    from /var/lib/hudson/.bundle/ruby/1.8/gems/polyglot-0.3.1/lib/polyglot.rb:64:in`require'
    from /usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:158:in `require'
    from /var/lib/hudson/.bundle/ruby/1.8/gems/capybara-envjs-0.1.2/lib/capybara/envjs.rb:5
    from /var/lib/hudson/.bundle/ruby/1.8/gems/polyglot-0.3.1/lib/polyglot.rb:64:in`polyglot_original_require'
    from /var/lib/hudson/.bundle/ruby/1.8/gems/polyglot-0.3.1/lib/polyglot.rb:64:in `require'
    from /usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:158:in`require'
    from ./spec/acceptance/acceptance_helper.rb:5
    from ./spec/acceptance/saved_candidate_search_feature_spec.rb:1:in `require'
    from ./spec/acceptance/saved_candidate_search_feature_spec.rb:1
    from /usr/local/lib/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/example_group_runner.rb:15:in`load'
    from /usr/local/lib/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/example_group_runner.rb:15:in `load_files'
    from /usr/local/lib/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/example_group_runner.rb:14:in`each'
    from /usr/local/lib/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/example_group_runner.rb:14:in `load_files'
    from /usr/local/lib/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/options.rb:133:in`run_examples'
    from /usr/local/lib/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/command_line.rb:9:in `run'
    from /usr/local/lib/ruby/gems/1.8/gems/rspec-1.3.0/bin/spec:5

**Comment by smparkes** [comment]
Happy to tweak this ... once I understand it.

You're not using Cucumber, but it's been required? Just having the gem there shouldn't cause this.

I don't actually use Cucumber, so I'm not exactly sure how the pieces fit together.

**Comment by mguterl** [comment]
We're using both RSpec and Cucumber, but we're slowly moving away from Cucumber.  

I haven't investigated much, but the Cucumber constant is defined at this point, despite it not having been required.

Maybe it has something to do with bundler, we have cucumber in our Gemfile in the test group which both Cucumber and RSpec use.

**Comment by smparkes** [comment]
Still not sure why you would get this, but I suppose it makes sense. Will be in 0.1.3.
