### ISSUE TITLE
Apparently not compatible with Rails 3

### ISSUE THREAD

**Issue by hakanensari** [smparkes/capybara-envjs#9]
It borks in Rails 3.

To replicate, check out the envjs branch at:

http://github.com/papercavalier/capybara-foo

**Comment by smparkes** [comment]
Replicated. Not sure yet if it's a Rails3 specific or not ... we'll see.

**Comment by smparkes** [comment]
I used to get a weird error on this (wrong number of args). Now I simply get a 'not found on page' so I'm not sure exactly what might or might not be broken.

Can you retest? Maybe with the new capy (and the new capy-envjs 0.1.3, which should be out before too long ...)

**Comment by thibaudgg** [comment]
+1, still having "wrong number of arguments (0 for 1)" with capy-envjs 0.1.3 & Rails3

**Comment by smparkes** [comment]
Are you sure you're getting capy-envjs-1.3? The github Gemfile is still calling out 1.2. And Capy 0.3.7.

Basically, I can't replicate this ... I'm not sure what's different between the environments we have.

Here's what I see right now:

http://gist.github.com/420289

I'm not 100% sure what the cause of the error is. Does look like you're calling out an element that doesn't exist, which is what the error message says. But I may be missing/misinterpreting something.

**Comment by hakanensari** [comment]
Sorry for getting back so late.

I just updated the Gemfile to capybara 3.8 and envjs 0.1.13 and am no longer getting the above error. And now that the tests are properly running, I see that the JS itself is buggy. Not sure what we were thinking :-)
